### ISSUE TITLE
Bug List ( 1/30/15 )

### ISSUE THREAD

**Issue by Ace18o** [Subterranean-Security/Crimson#32]
Feel free to add to this/remove from this.
1. When full screening the control panel and resizing the "Log" on the bottom of the panel causes the size to change when the panel is re-minimized.
2. Keylogger doesn't update the stats until the panel is closed.
3. When detaching the "tabs" the size of the windows are messed up.
4. No way to reattach "tabs"
5. When re-toggling the missing "tab" it doesn’t appear at all, even after restarting the control panel.
6. Restoring all "tabs" doesn’t work.
7. Chat STILL doesn’t work inside the control panel.
8. Right clicking on clipboard content brings up a NOT FOUND menu??
9. Buttons are greyed but are still toggle-able. ( Update is greyed but I can still access the update window )
10. Map has no scroll function.
11. The "log" on the bottom of the control panel doesn’t keep resize changes. ( _Maximizing the window then changing the log size then minimizing it then maximizing it it doesn’t keep the size it was set to the first time )
    (_) )
12. When using shell every time you enter a new command it goes back to the top of the shell window.
13. When using shell, the command "exit" breaks the current shell and causes crimson to report an error. ( This Needs to be fixed to insure the crimson servers don’t get spammed. )
14. Screen shots seem to work once and a while.
15. When the "Share Screen" option is toggled the chat window doesn’t pop up
16. Chat freezes..
17. If crimson hangs to long the notification won’t be showed but a blue box will be and it will stay till crimson  
    gets a new notification, or until "Never Show Notifications is toggled"
18. Looks like the old control panel not opening after a error is back.
19. After restarting crimson local host connections no longer appear.
20. Listener names no longer appear.
21. https://subterranean-security.com/ and CrimsonRat.org are still listed on the About Window.
22. http://subterranean-security.com/ is under maintenance ;)
23. http_s_://subterranean-security.com/ has a SSL error.

**Comment by Subterranean-Security** [comment]
Thanks. I'm on hiatus for a few months right now, but I will work on these when I return. The repository is still a mess, but it will get better.

**Comment by Ace18o** [comment]
I saw on the site, take your time. Ill keep posting in this if I find any more.

(MrToxic from the forums)

**Comment by Subterranean-Security** [comment]
Much appreciated as always.
